# Generated by Django 5.0.1 on 2024-01-23 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_rename_timestamp_post_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='time',
            new_name='timestamp',
        ),
    ]
